import { Inclusive_Sans } from "next/font/google";
import "./globals.css";
import Menu from "./menu";
import { BsInstagram } from "react-icons/bs";
import { FaWhatsapp } from "react-icons/fa";
import { RiDiscordLine } from "react-icons/ri";
import { SlSocialLinkedin } from "react-icons/sl";

const mainFontFamily = Inclusive_Sans({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-b4">
      <body
        className={`${mainFontFamily.className} bg-[#000014] flex h-screen`}
      >
        <header className="mx-auto flex justify-between gap-96 pt-4">
          <div className="font-bold text-4xl text-teal-300">
            theo vargas<strong className="text-red-700">.</strong>
          </div>
          <div className="flex justify-center text-teal-300 gap-10 pt-4 text-xl">
            <a>
              <BsInstagram className="cursor-pointer hover:animate-bounce hover:text-red-600" />
            </a>
            <a>
              <FaWhatsapp className="cursor-pointer hover:animate-bounce hover:text-red-600" />
            </a>
            <a>
              <RiDiscordLine className="cursor-pointer hover:animate-bounce hover:text-red-600" />
            </a>
            <a>
              <SlSocialLinkedin className="cursor-pointer hover:animate-bounce hover:text-red-600" />
            </a>
          </div>
        </header>
        <main className="flex items-center">
          <Menu />
        </main>
      </body>
    </html>
  );
}
