import { Inclusive_Sans } from "next/font/google";
import "./globals.css";
import Menu from "./menu";
import Header from "./head";

const mainFontFamily = Inclusive_Sans({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <div className="bg-000014 bg-cover bg-no-repeat h-screen w-full overflow-hidden">
        <Header />
        <Menu />
        {children}
      </div>
    </>
  );
}
