import { Inclusive_Sans } from "next/font/google";
import "./globals.css";
import Menu from "./menu";
import HeaderLayout from "./head";
import TopLefImg from "./topleftimg";

const mainFontFamily = Inclusive_Sans({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html className="bg-000014 bg-cover bg-no-repeat h-screen w-full overflow-hidden z-10">
      <body>
        <main>
          <TopLefImg />
          <HeaderLayout />
          <Menu />
          {children}
        </main>
      </body>
    </html>
  );
}
